[package]
name = "sim_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9", features = ["dynamic","jpeg"] }
iyes_loopless = "0.9.1"
rand = "0.8.5"
#bevy_mod_picking = { git = "https://github.com/aevyrie/bevy_mod_picking", branch = "beta", features = ["backend_sprite", "debug"]}
bevy_mod_picking = { path = "./dependencies/bevy_mod_picking-beta", features = ["backend_sprite", "debug"]}
bevy_egui = "0.18.0"
strum = "0.24.1"
strum_macros = "0.24"
bevy_framepace = { version = "0.10.0", default-features = true }
enum_dispatch = "0.3.11"
# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3


